[workspace]
resolver = "3"
members = ["client", "server", "common"]

[workspace.dependencies]
tokio = { version = "1.52.3", features = ["full"] }

tun-rs = { version = "2.8.6", features = ["async", "async_framed"] }
etherparse = "0.20.2"
quinn = { version = "0.11.11", features = ["rustls-aws-lc-rs", "rustls-ring"] }
rustls = "0.23.41"
rcgen = "0.14.8"

anyhow = "1.0.103"
dashmap = "6.2.1"
bytes = "1.12.0"
