[package]
name = "tun-server"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }

tokio.workspace = true

tun-rs.workspace = true
quinn.workspace = true
etherparse.workspace = true
rustls.workspace = true
rcgen.workspace = true

anyhow.workspace = true
dashmap.workspace = true
bytes.workspace = true
